### ISSUE TITLE
Engels of Nederlands

### ISSUE THREAD

**Issue by lottekoblens** [samclarkb/frontend-applications#4]
Kies of je je code in het Engels wil schrijven of in het Nederlands. Sommige functies hebben een Nederlandse naam, andere juist weer een Engelse.

**Comment by samclarkb** [comment]
Ik heb alle functies en code comments nu in het Nederlands geschreven. Dit is voor mij beter te lezen

**Comment by samclarkb** [comment]
Thanks voor de tip!
